name: Build & Deploy to OVH

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t registry.fmaret.duckdns.org/overbot:latest ./server

      - name: Login to private registry
        run: echo ${{ secrets.REGISTRY_PASSWORD }} | docker login registry.fmaret.duckdns.org -u ${{ secrets.REGISTRY_USERNAME }} --password-stdin

      - name: Push Docker image backend
        run: docker push registry.fmaret.duckdns.org/overbot:latest
